---
title: "Resolución Actividad 2 máster Bioinformática UNIR (2024)"
author: "Elena Varea Jiménez, Cristina Ruiz Roldán, Leire Martínez Montoya, Andrés Cayuela Salas"
date: "2024-06-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)

# Introducción a la programación científica

## Actividad 2. Github: Crear un repositorio en github. Control de versiones.


```

### Tabla descriptiva

```{r, include=TRUE}

# selecciono el PC1 y PC2
pc1_values <- pca_alimentos_nutrientes$x[,1]
pc2_values <- pca_alimentos_nutrientes$x[,2]

# Se seleccionan las variables que interesan para la tabla descriptiva1 (correspondiente al PC1)
# Se calculan los terciles del PC1 y se ponen las etiquetas
# Para establecer la lista de variables nos basamos en el gráfico de contribución al PC1 (fviz_contrib)
descriptiva1 <- subset(data, select = c(nutriente7, nutriente4, nutriente2, nutriente13, nutriente10, nutriente12, nutriente11, nutriente14, nutriente8, nutriente19))
descriptiva1$componente1_t <- cut(pc1_values, 
                     breaks = c(-Inf, 1/3, 2/3, Inf), 
                     labels = c("tercil 1", "tercil 2", "tercil 3"), 
                     include.lowest = TRUE)
# Se seleccionan las variables que interesan para la tabla descriptiva2 (correspondiente al PC2)
# Se calculan los terciles del PC2 y se ponen las etiquetas
# Para establecer la lista de variables nos basamos en el gráfico de contribución al PC2 (fviz_contrib)
descriptiva2 <- subset(data, select = c(carnes, lacteos, verdura, nutriente19, fruta, alimento27, nutriente6, nutriente16, alimento20, alimento52))
descriptiva2$componente2_t <- cut(pc2_values, 
                     breaks = c(-Inf, 1/3, 2/3, Inf), 
                     labels = c("tercil 1", "tercil 2", "tercil 3"), 
                     include.lowest = TRUE)


# Tabla descriptiva con contraste de hipótesis para terciles de PC1
tabla1 <- descriptiva1 %>%
  tbl_summary(
    by = componente1_t,  
    statistic = list(all_continuous() ~ "{median} ({p25}-{p75})", all_categorical() ~ "{n} ({p}%)"),
    type = everything() ~ "continuous",
    digits = everything() ~ 1
  ) %>%
  add_p(
    test = list(
      all_continuous() ~ "kruskal.test",
      all_categorical() ~ "chisq.test"
    ),
    pvalue_fun = ~ style_pvalue(.x, digits = 3)
  )

tabla1
```

```{r, include=TRUE}
# Tabla descriptiva con contraste de hipótesis para terciles de PC2

tabla2 <- descriptiva2 %>%
  tbl_summary(
    by = componente2_t,  
    statistic = list(all_continuous() ~ "{median} ({p25}-{p75})", all_categorical() ~ "{n} ({p}%)"),
    type = everything() ~ "continuous",
    digits = everything() ~ 1
  ) %>%
  add_p(
    test = list(
      all_continuous() ~ "kruskal.test",
      all_categorical() ~ "chisq.test"
    ),
    pvalue_fun = ~ style_pvalue(.x, digits = 3)
  )

tabla2
```

```{r, include=TRUE}
# Se combinan las dos tablas
tabla_combinada <- tbl_merge(
  tbls = list(tabla1, tabla2),
  tab_spanner = c("**Componente 1**", "**Componente 2**")
)
tabla_combinada

# Convertir la tabla a un objeto de FlexTable para poder editarla
tabla_flex2 <- as_flex_table(tabla_combinada)

tabla_flex2 <- set_caption(tabla_flex2, as_paragraph(as_b('Tabla 2. Tabla descriptiva')),  align_with_table = FALSE)
tabla_flex2 <- set_table_properties(tabla_flex2, layout = "autofit", width = 1)


```

### Modelo de regresión logística

```{r, include=TRUE}
# Se incluyen en el dataframe "data" las variables de los terciles de PC1 y PC2
data$componente1_t <- descriptiva1$componente1_t
data$componente2_t <- descriptiva2$componente2_t

# La variable diab_prev (prevalencia de diabetes) es una variable dicotómica "0" "1"
levels(as.factor(data$diab_prev))

# Modelo1 de regresión logística que mide la asociación entre el componente principal 1 (PC1) y la prevalencia de diabetes (diab_prev). Se toman sexo, edad, IMC y tabaco como variables de ajuste
modelo1 <- glm(diab_prev ~ componente1_t + sexo + edad + IMC + tabaco, data = data, family = binomial())
summary(modelo1)
# Se sacan los odds ratios (OR) de modelo1
OR_modelo1 <- exp(cbind(OR = coef(modelo1), confint(modelo1)))

# Modelo2 de regresión logística que mide la asociación entre el componente principal 2 (PC2) y la prevalencia de diabetes (diab_prev). Sexo, edad, IMC y tabaco como variables de ajuste:
modelo2 <- glm(diab_prev ~ componente2_t + sexo + edad + IMC + tabaco, data = data, family = binomial())
summary(modelo2)
# Se sacan los odds ratios (OR) de modelo2
OR_modelo2 <- exp(cbind(OR = coef(modelo2), confint(modelo2)))

# Se obtiene la tabla de la regresión para los dos modelos
tbl_modelo1 <- tbl_regression(modelo1, exponentiate = TRUE) %>%
  add_global_p()

tbl_modelo2 <- tbl_regression(modelo2, exponentiate = TRUE) %>%
  add_global_p()

# Combinar las tablas en una tabla final
tbl_final <- tbl_merge(
  tbls = list(tbl_modelo1, tbl_modelo2),
  tab_spanner = c("**Terciles componente 1**", "**Terciles componente 2**")
) %>%
  modify_header(label = "**Terciles**")
# Modificar las notas al pie
tbl_final <- tbl_final %>%
  modify_footnote(
    update = everything() ~ "Variables de ajuste: sexo, edad, IMC y tabaco"
  )
tbl_final

# Convertir la tabla a un objeto de FlexTable para poder editarla
tabla_flex3 <- as_flex_table(tbl_final)

tabla_flex3 <- set_caption(tabla_flex3, as_paragraph(as_b('Tabla 3. Tabla de regresión logística')),  align_with_table = FALSE)
tabla_flex3 <- set_table_properties(tabla_flex3, layout = "autofit", width = 1)

```